const Blog = require('../models/Blog');
const AppError = require('../utils/AppError');

const getAllBlogs = async () => {
    return await Blog.find().populate('author', 'name email');
};

const getBlogBySlug = async (slug) => {
    const blog = await Blog.findOne({ slug }).populate('author', 'name email');
    if (!blog) {
        throw new AppError('Blog not found', 404);
    }
    return blog;
};

const getBlogById = async (id) => {
    const blog = await Blog.findById(id).populate('author', 'name email');
    if (!blog) {
        throw new AppError('Blog not found', 404);
    }
    return blog;
};

const createBlog = async (blogData, file) => {
    if (file) {
        blogData.image = file.path;
    }
    return await Blog.create(blogData);
};

const updateBlogById = async (id, updateData, file) => {
    let blog = await Blog.findById(id);
    if (!blog) {
        throw new AppError('Blog not found', 404);
    }

    if (file) {
        updateData.image = file.path;
    }

    if (updateData.slug) {
        blog.slug = updateData.slug;
    } else if (updateData.title && updateData.title !== blog.title) {
        // Slug will be regenerated by the pre-save hook if we just set title, but doing it manually is fine too
        blog.slug = updateData.title
            .toLowerCase()
            .replace(/[^a-z0-9 -]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-');
    }

    if (updateData.title && typeof updateData.title === 'string') blog.title = updateData.title;
    if (updateData.content && typeof updateData.content === 'string') blog.content = updateData.content;
    if (updateData.image && typeof updateData.image === 'string') blog.image = updateData.image;

    await blog.save();
    return blog;
};

const deleteBlogById = async (id) => {
    const blog = await Blog.findByIdAndDelete(id);
    if (!blog) {
        throw new AppError('Blog not found', 404);
    }
    return {};
};

module.exports = {
    getAllBlogs,
    getBlogBySlug,
    getBlogById,
    createBlog,
    updateBlogById,
    deleteBlogById
};
